<a href="https://colab.research.google.com/github/mbarragan744/clase-IA/blob/main/Naive_Bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ENTRENAMIENTO DE UN MODELO DE MACHINE LEARNING

importar las librerias

declarar el modelo

entrenar(80%) (X_train, y_train)

predecir(20%)

validar las metricas para verificar que el modelo lo haga bien

persistencia

#----------------------------------------------------------------------#
PREPROCESAMIENTO

importar las librerias

declarar el modelo

entrenar

transformo

persistencia (opcional)

#IMPLEMENTACION DEL TEOREMA DE BAYES (NAIVE BAYES)

In [4]:
import pandas as pd
from sklearn.naive_bayes import MultinomialNB
from sklearn.preprocessing import LabelEncoder

# Crear el conjunto de datos
data = {
    "Horas de Estudio": ["Alta", "Baja", "Baja", "Alta", "Alta"],
    "Asistencia": ["Buena", "Buena", "Mala", "Mala", "Buena"],
    "Resultado": ["Sí", "No", "No", "Sí", "Sí"]
}

df = pd.DataFrame(data)
df


Horas de Estudio Asistencia Resultado
0             Alta      Buena        Sí
1             Baja      Buena        No
2             Baja       Mala        No
3             Alta       Mala        Sí
4             Alta      Buena        Sí

In [5]:

# Crear LabelEncoders por columna para asegurar consistencia.
encoders = {col: LabelEncoder() for col in df.columns}

# Codificar el DataFrame completo
df_encoded = df.apply(lambda col: encoders[col.name].fit_transform(col))

df_encoded

Horas de Estudio  Asistencia  Resultado
0                 0           0          1
1                 1           0          0
2                 1           1          0
3                 0           1          1
4                 0           0          1

In [7]:
#se le hizo persistencia y se guardó en una carpeta
import joblib as jb
jb.dump(encoders, 'encoders.bin')


['encoders.bin']

In [24]:
# Separar características y etiqueta
X = df_encoded[["Horas de Estudio", "Asistencia"]]  #X = df_encoded.drop("Resultado", axis=1)   ESTE ES MAS EFICIENTE
y = df_encoded["Resultado"]

# Entrenar modelo Naive Bayes
model = MultinomialNB()
model.fit(X, y)

MultinomialNB()

In [25]:
nuevos=[["Alta","Mala"],["Baja","Buena"],["Baja","Mala"]]
df_nuevos=pd.DataFrame(nuevos,columns=["Horas de Estudio", "Asistencia"])
df_nuevos

Horas de Estudio Asistencia
0             Alta       Mala
1             Baja      Buena
2             Baja       Mala

In [26]:
X_nuevos = df_nuevos.apply(lambda col: encoders[col.name].transform(col))
X_nuevos

Horas de Estudio  Asistencia
0                 0           1
1                 1           0
2                 1           1

In [34]:
prediccion= model.predict(X_nuevos)
prediccion

array([1, 0, 1])

In [35]:

prediccion= encoders["Resultado"].inverse_transform(model.predict(X_nuevos))
prediccion

array(['Sí', 'No', 'Sí'], dtype=object)

In [38]:
import pickle # una libreria para hacer persistencia

# Guardar el modelo utilizando pickle
with open('mimillon.pkl', 'wb') as file:
    pickle.dump(model, file)

print("Modelo guardado exitosamente.")

Modelo guardado exitosamente.


In [37]:
jb.dump(model, 'mimillon.bin')

['mimillon.bin']

#SE NECESITAN MINIMO 100 DATOS PARA HACER UN MODELO

In [40]:
import pandas as pd

# Cargar el conjunto de datos
url = "https://raw.githubusercontent.com/adiacla/bigdata/refs/heads/master/pacientes.csv"
df = pd.read_csv(url)

# Mostrar las primeras filas para inspeccionar los datos
df

edad  colesterol  problema_cardiaco
0    63.0       233.0                  1
1     NaN       250.0                  0
2    37.0       250.0                  0
3    41.0       204.0                  0
4    56.0       236.0                  1
..    ...         ...                ...
297  63.0       187.0                  0
298  63.0       197.0                  0
299  59.0       176.0                  0
300  57.0       241.0                  1
301  45.0       264.0                  1

[302 rows x 3 columns]

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 302 entries, 0 to 301
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   edad               300 non-null    float64
 1   colesterol         300 non-null    float64
 2   problema_cardiaco  302 non-null    int64  
dtypes: float64(2), int64(1)
memory usage: 7.2 KB


In [42]:
df.describe()

edad  colesterol  problema_cardiaco
count  300.000000  300.000000         302.000000
mean    54.303333  247.280000           0.493377
std      9.090661   51.855681           0.500786
min     29.000000  126.000000           0.000000
25%     47.000000  211.750000           0.000000
50%     55.000000  242.500000           0.000000
75%     61.000000  275.250000           1.000000
max     77.000000  564.000000           1.000000

In [43]:
df.isna().sum()

edad                 2
colesterol           2
problema_cardiaco    0
dtype: int64

In [44]:
# Imputar los valores nulos con la mediana
df['edad'] = df['edad'].fillna(df['edad'].median())
df['colesterol'] = df['colesterol'].fillna(df['colesterol'].median())

# Comprobar que no hay valores nulos
print(df.isnull().sum())

edad                 0
colesterol           0
problema_cardiaco    0
dtype: int64


In [47]:
from sklearn.preprocessing import StandardScaler
import joblib

# Asumiendo que 'df' ya es tu DataFrame
# Crear el objeto scaler
scaler = StandardScaler()

# Normalizar las características numéricas
df[['edad', 'colesterol']] = scaler.fit_transform(df[['edad', 'colesterol']])

# Guardar el scaler en un archivo .joblib para usarlo posteriormente
joblib.dump(scaler, 'scaler.pkl')

# Ver los primeros datos después de la normalización
print(df)    #si le pongo df.head(se pone algun numero), mostrará la cantidad de filas que se le indiquen

         edad  colesterol  problema_cardiaco
0    0.960918   -0.276136                  1
1    0.076507    0.053328                  0
2   -1.913416    0.053328                  0
3   -1.471211   -0.838164                  0
4    0.187059   -0.217996                  1
..        ...         ...                ...
297  0.960918   -1.167628                  0
298  0.960918   -0.973825                  0
299  0.518713   -1.380810                  0
300  0.297610   -0.121094                  1
301 -1.029006    0.324651                  1

[302 rows x 3 columns]


In [48]:
df.shape

(302, 3)

#VISTA MINABLE= DATOS LIMPIOS (PERFECTOS)
SON LOS QUE SE DIVIDEN 80-20 PARA EL ENTRENAMIENTO DEL MODELO

In [49]:
from sklearn.model_selection import train_test_split

# Definir las características y la etiqueta
X = df[['edad', 'colesterol']]
y = df['problema_cardiaco']

# Dividir en entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print(f"Tamaño del conjunto de entrenamiento: {X_train.shape}")
print(f"Tamaño del conjunto de prueba: {X_test.shape}")

Tamaño del conjunto de entrenamiento: (241, 2)
Tamaño del conjunto de prueba: (61, 2)


In [50]:
from sklearn.naive_bayes import GaussianNB

# Crear el modelo Naive Bayes
nb_model = GaussianNB()

In [51]:
# Entrenar el modelo
nb_model.fit(X_train, y_train)

GaussianNB()

In [52]:
# Realizar predicciones
y_pred_nb = nb_model.predict(X_test)

print("Predicciones de los pacientes en y_test")

y_pred_nb

Predicciones de los pacientes en y_test


array([0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1])

In [53]:
print("Valores reales de y_test")
y_test.to_numpy()

Valores reales de y_test


array([0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1])

In [ ]:
# Evaluar el modelo
from sklearn.metrics import accuracy_score, confusion_matrix, roc_auc_score, roc_curve  #ROC= Area bajo la curva